monolog:
  channels:
    - deprecation
    - some
    - rmq_logs

when@dev:
  monolog:
    handlers:
      main:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: debug
        channels: ["!event"]
      some:
        type: stream
        path: "%kernel.logs_dir%/some-%kernel.environment%.log"
        level: debug
        channels: [ "some" ]
      console:
        type: console
        process_psr_3_messages: false
        channels: ["!event", "!doctrine", "!console"]
      rmq_logs:
        type: service
        id: monolog.handler.rabbitmq
        level: debug
        channels: ["rmq_logs"]

when@prod:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: error
        handler: nested
        excluded_http_codes: [404, 405]
        buffer_size: 50
      nested:
        type: service
        id: monolog.handler.rabbitmq
        level: debug
      console:
        type: console
        process_psr_3_messages: false
        channels: ["!event", "!doctrine"]
      deprecation:
        type: service
        id: monolog.handler.rabbitmq
        channels: [deprecation]
        level: debug
