old_sound_rabbit_mq:
    connections:
        default:
            host: '%env(RABBITMQ_HOST)%'
            port: '%env(RABBITMQ_PORT)%'
            user: '%env(RABBITMQ_USER)%'
            password: '%env(RABBITMQ_PASSWORD)%'
            vhost: '%env(RABBITMQ_VHOST)%'
            lazy: true
            connection_timeout: 3
            read_write_timeout: 3

    producers:
        logs:
            connection: default
            exchange_options: {name: 'logs_exchange', type: direct}
    consumers:
        logs:
            connection: default
            exchange_options: {name: 'logs_exchange', type: direct}
            queue_options: {name: 'logs_queue'}
            callback: App\Command\Consumer\LogsConsumer